class TaskStatus(PermissionError): ...

class TaskCannotStart(TaskStatus): ...
class TaskCannotCompleted(TaskStatus): ...
class TaskCannotCancel(TaskStatus): ...
class DeadlineHasExpired(TaskStatus): ...
class UnavailableID(TaskStatus): ...
class TaskAlreadyExists(TaskStatus): ...

class TaskNotFind(ValueError): ...

class ParsingError(ValueError): ...